export TMP=/tmp

./download-json-files.sh > $TMP/aws.json || exit 1
cat $TMP/aws.json | npx @walmartlabs/json-to-simple-graphql-schema| sed -e "s/AutogeneratedMainType/Aws/g" > $TMP/aws-schema.graphql || exit 2
cat $TMP/aws-schema.graphql aws-schema-query.graphql >  ../resources/aws-schema.graphql.new
