targetfile="aws-schema.graphql"

echo "{"
prefix=""
while IFS=, read -r cmd object
do
    echo "$prefix\"$object\":"
    aws $cmd --max-items 5 > $TMP/$object
    cat $TMP/$object
    prefix=","
done < aws.csv

echo "}"

# | npx @walmartlabs/json-to-simple-graphql-schema| sed -e "s/AutogeneratedMainType/AWS/g"
